name: ctrlx-deconz # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
summary: deconz # 79 char long summary
description: |
  deconz
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
adopt-info: deconz

parts:
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
  deconz:
    source: .
    plugin: dump
    source-type: deb
    build-packages:
      - wget
    stage-packages:
    - qt5-default
    - curl
    - kmod
    - libcap2-bin
    - libqt5core5a
    - libqt5gui5
    - libqt5network5
    - libqt5serialport5
    - libqt5sql5
    - libqt5websockets5
    - libqt5widgets5
    - lsof
    - sqlite3
    - tigervnc-standalone-server
    - tigervnc-common
    - xfonts-base
    - xfonts-scalable
    override-pull: |
      export DECONZ_VERSION=$(cat $SNAPCRAFT_STAGE/VERSION_DECONZ)
      wget -q -O- http://deconz.dresden-elektronik.de/ubuntu/stable/deconz-2.05.88-qt5.deb | dpkg -x - "$SNAPCRAFT_PART_SRC"
      snapcraftctl set-version "${DECONZ_VERSION}+$(date +%Y%m%d%H%M%S)"
    after:
    - configs
  scripts:
    source: ./scripts
    plugin: dump
    organize:
      '*': bin/

apps:
  deCONZ:
    command: bin/start.sh
    daemon: simple
    plugs: 
      - network-bind
      - network
      - conbeeii
      - system-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins
      #QT_DEBUG_PLUGINS: 1
      DEBIAN_FRONTEND: noninteractive
      DECONZ_WEB_PORT: 8087
      DECONZ_WS_PORT: 8088
      DEBUG_INFO: 2
      DEBUG_ERROR: 2
      DEBUG_APS: 0
      DEBUG_ZCL: 0
      DEBUG_ZDP: 0
      DEBUG_OTAU: 0
      DECONZ_DEVICE: /dev/ttyACM0
      DECONZ_VNC_MODE: 0
      DECONZ_VNC_DISPLAY: 0
      DECONZ_VNC_PASSWORD: changeme
      DECONZ_VNC_PORT: 5900
      DECONZ_UPNP: 1

plugs:
  conbeeii:
    interface: serial-port
  # system-files:
  #   interface: system-files
  #   write:
  #     - /dev

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

layout:
  /usr/share/deCONZ/webapp:
    bind: $SNAP/usr/share/deCONZ/webapp
  # /var/lock/LCK..serial_by-id_usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2219993-if00:
  #   bind-file: $SNAP_DATA/var/lock/LCK..serial_by-id_usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2219993-if00
  # /etc/locks:
  #   bind: $SNAP_DATA/etc/locks
  # /var/spool/locks:
  #   bind: $SNAP_DATA/var/spool/locks
  # /var/spool/uucp:
  #   bind: $SNAP_DATA/var/spool/uucp
  # /usr/bin/GCFFlasher_internal:
  #   bind-file: $SNAP/usr/bin/GCFFlasher_internal