name: ctrlx-deconz # you probably want to 'snapcraft register <name>'
title: deCONZ
base: core18 # the base snap is the execution environment for this snap
summary: Control software for Zigbee networks # 79 char long summary
description: |
  deCONZ is an easy to use control software, with which you can set up and control Zigbee networks of any size without further programming effort.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
adopt-info: deconz

parts:
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
  qtserialport:
    plugin: qmake
    source: git://code.qt.io/qt/qtserialport.git
    source-tag: v5.9.5
    build-packages:
      - qtbase5-dev
      - qtbase5-private-dev
    override-pull: |
      set -x
      snapcraftctl pull
      ls $SNAPCRAFT_PART_SRC
      git apply $SNAPCRAFT_STAGE/qtserialport.patch
    project-files:
    - qtserialport.pro
    after:
    - configs
  deconz:
    source: .
    plugin: dump
    source-type: deb
    build-packages:
      - wget
    stage-packages:
    - qt5-default
    - curl
    - kmod
    - libcap2-bin
    - libqt5core5a
    - libqt5gui5
    - libqt5network5
    - libqt5sql5
    - libqt5websockets5
    - libqt5widgets5
    - lsof
    - sqlite3
    # VNC
    - tightvncserver
    - xfonts-base
    # For tigervnc
    #- perl-modules-5.26
    #- util-linux
    override-pull: |
      export DECONZ_VERSION=$(cat $SNAPCRAFT_STAGE/VERSION_DECONZ)
      wget -q -O- http://deconz.dresden-elektronik.de/ubuntu/stable/deconz-2.05.88-qt5.deb | dpkg -x - "$SNAPCRAFT_PART_SRC"
      snapcraftctl set-version "${DECONZ_VERSION}+$(date +%Y%m%d%H%M%S)"
    after:
    - configs
    - qtserialport
  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/
  scripts:
    plugin: dump
    source: src/utilities
  

apps:
  deconz:
    command: bin/start.sh
    daemon: simple
    post-stop-command: bin/vncserver -kill :2
    plugs: 
      - network-bind
      - network
      - conbeeii
      - system-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins
      #QT_DEBUG_PLUGINS: 1
      DEBIAN_FRONTEND: noninteractive
      DECONZ_WEB_PORT: 8087
      DECONZ_WS_PORT: 8088
      DEBUG_INFO: 2
      DEBUG_ERROR: 2
      DEBUG_APS: 0
      DEBUG_ZCL: 0
      DEBUG_ZDP: 0
      DEBUG_OTAU: 0
      DECONZ_DEVICE: /dev/ttyACM0
      DECONZ_VNC_MODE: 0
      DECONZ_VNC_PASSWORD: changeme
      DECONZ_VNC_PORT: 5900
      DECONZ_UPNP: 1
      PERL5LIB: $SNAP/usr/share/perl/5.26:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.26

plugs:
  conbeeii:
    interface: serial-port

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

layout:
  /usr/share/deCONZ/webapp:
    bind: $SNAP/usr/share/deCONZ/webapp